name: ssljax

channels:
    - conda-forge
    - pytorch

dependencies:
    - python>=3.8
    - pip
    - pytest
    - numpy
    - pytorch
    - coverage
    - pre-commit
    - pip:
        - jax>=0.1.71
        - optax
        - sphinx>=3.4.3
        - nbsphinx>=0.8.1
        - nbsphinx-link>=1.3.0
        - sphinx-rtd-theme>=0.5.1
        - sphinxcontrib-bibtex
        - sphinx-autoapi>=1.8.3
        - sphinx-copybutton
        - ipython
        - tqdm
        - flax
        - base58
        - dill
        - overrides
        - hydra-core
        - torchvision
        - tensorboardX
        - tensorboard
        - tensorflow
        - parameterized
