name: ssljax

channels:
    - conda-forge
    - pytorch

dependencies:
    - python>=3.8
    - pip==21.2.2
    - pytest>=6.2.2
    - numpy
    - pytorch
    - coverage==5.5
    - pre-commit==2.13.0
    - pip:
        - jax>=0.1.71
        - optax
        - sphinx>=3.4.3
        - nbsphinx>=0.8.1
        - nbsphinx-link>=1.3.0
        - sphinx-rtd-theme>=0.5.1
        - sphinx-autoapi>=1.8.3
        - ipython
        - tqdm
        - flax
        - base58
        - dill
        - overrides
